# 生成代码的根包名
basePackage=cn.org.expect.nas
# 数据库表统一前缀
tablePrefix=nas_
# 父类型支持 ${entity} 占位符；留空表示不继承
daoSuperInterface=cn.org.expect.nas.dao.BaseDao<${entity}>
mapperSuperInterface=com.baomidou.mybatisplus.core.mapper.BaseMapper<${entity}>
entitySuperClass=cn.org.expect.nas.entity.AbstractTemplateEntity
# 全部字段与指定数据库字段的附加注解，使用 | 分隔
entityFieldAnnotations=
entityFieldAnnotations.id=jakarta.validation.constraints.NotNull
# 附加注解需要的 import，使用逗号分隔
entityAnnotationImports=jakarta.validation.constraints.NotNull
# 数据库类型映射可继续增加 sqlTypeMappings.<类型>
sqlTypeMappings.LONG=BIGINT
sqlTypeMappings.DATETIME=TIMESTAMP
sqlTypeMappings.BLOB=BYTEA
sqlTypeMappings.CLOB=TEXT
